/*=========================================================
05_1_Executive_KPIs.sql

Executive KPI analysis for the DataCo Supply Chain dataset.
Each query answers a key business question used in the
Executive Overview dashboard.
=========================================================*/

/* KPI 1.1 Total Sales
What is the total revenue generated by the business? */

SELECT 
	ROUND(SUM(sales),2) AS total_sales
FROM fact_order_items;
----------------------------------------------------------------

/* KPI 1.2 Total Profit
What is the total profit generated by the business?*/

SELECT
    ROUND(SUM(order_profit_per_order), 2) AS total_profit
FROM fact_order_items;
----------------------------------------------------------------

/* KPI 1.3 — Profit Margin %
What percentage of sales revenue is retained as profit? */

SELECT 
	ROUND(
		SUM(order_profit_per_order)/SUM(sales) * 100 ,
        2) AS profit_margin_pct
FROM fact_order_items;
----------------------------------------------------------------

/* KPI 1.4 — Total Orders
How many orders were placed by customers?*/

SELECT
	COUNT(DISTINCT order_id) AS total_orders
FROM fact_order_items;
----------------------------------------------------------------

/* KPI 1.5 — Average Order Value (AOV)
What is the average revenue generated per customer order? */
SELECT
	ROUND(
		SUM(sales) / COUNT(DISTINCT order_id), 
        2) AS average_order_value
FROM fact_order_items;
----------------------------------------------------------------

/* KPI 1.6 — Total Units Sold
How many individual product units were sold during the reporting period?*/

SELECT
	SUM(order_item_quantity) AS total_units_sold
FROM fact_order_items;
----------------------------------------------------------------

/* KPI 1.7 — Average Profit per Order
On average, how much profit does each customer order generate?*/

SELECT
	ROUND(
		SUM(order_profit_per_order) / COUNT(DISTINCT order_id),
        2) AS average_profit_per_order
FROM fact_order_items;
